### ISSUE TITLE
求助大神一个问题如图

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/openwrt-feeds#1]
![qq 20180510205756](https://user-images.githubusercontent.com/26851715/39870697-da7193f2-5494-11e8-8128-cf643512ce7c.png)
4.4.131内核 mater插件库 点击保存应用后 就会这样 单独执行shell就没有问题
以前就没有这个问题 都能正常使用 而且不止这个一个插件

**Comment by kuoruan** [comment]
这个 LuCI 有 BUG，找作者反馈去

**Comment by fuqiang03** [comment]
原作者已经找不到了，这个是LEDE4月18号更新后出现的。
